language: objective-c  #1
osx_image: xcode8.3 #2
xcode_project: MovingHelper.xcodeproj #3
xcode_scheme: MovingHelper #4
xcode_sdk: iphonesimulator10.3 #5

script:
- xcodebuild clean build -sdk iphonesimulator10.3 -project MovingHelper.xcodeproj -scheme MovingHelper CODE_SIGNING_REQUIRED=NO
